### PR TITLE
Initial compatibility

### PR DESCRIPTION
**Pull request by VicDeo**

### CODE REVIEW

**Comment by JKawohl** [comment]
I run into {"reqId":"aJ2YyXoO4oy7BvNuNbYK","level":2,"time":"2018-02-21T08:49:08+00:00","remoteAddr":"91.39.155.39","user":"John","app":"cms_pico","method":"PUT","url":"\/index.php\/apps\/cms_pico\/personal\/website","message":"{\"name\":\"test\",\"error\":\"Die Vorlagendatei kann nicht in diesem Verzeichnis erstellt werden\"}"}  Which tranlates to: the template file could not be created

**Comment by VicDeo** [comment]
@JKawohl 
Confirmed. 
All click handlers are registered twice on the Settings page so it creates the site and then tries to create it once again. So it shows the error for the second attempt  but the website is created nevertheless.

**Comment by VicDeo** [comment]
@JKawohl fixed ;)

**Comment by JKawohl** [comment]
alright, next step: It doesn't seem to get the right path for the site:
When i create a site: 
bildschirmfoto 2018-02-22 um 10 18 04
I get this by clicking on the link:
bildschirmfoto 2018-02-22 um 10 19 09

Which roughly translates to:
" File not found
The selected document was not found on the server."

**Comment by VicDeo** [comment]
@JKawohl you need setup apache rules as specified [at the admin tab](https://github.com/VicDeo/cms_pico/blob/master/screenshots/apache.png?raw=true)

otherwise your site will be accessible only via `index.php/apps/cms_pico/pico/hfkjshfdkj`

**Comment by JKawohl** [comment]
I am not sure where to configure this in apache. In my ownCloud.conf or in the 000-default.conf ?

**Comment by VicDeo** [comment]
@JKawohl I'm not familiar with apache config that much
try adding 
```
RewriteRule /sites/(.*) https://YOUR.DOMAIN.TLD/index.php/apps/cms_pico/pico/$1 [QSA,L]
```
after this line  https://github.com/owncloud/core/blob/master/.htaccess#L69

**Comment by VicDeo** [comment]
Icon has been fixed

**Pull request merged**
